'use strict';

module.exports = {
  up : function (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('items',[{
  "name": "Avalanche",
  "description": "Gyps fulvus",
  "price": "5.34",
  "manufacturer": "Sumatriptan Succinate",
  "model": "G-Series 2500",
  "dimensions": "XS",
  "notes": "Office Assistant I",
  "image": "https://robohash.org/laboriosamidpariatur.png?size=100x100&set=set1",
  "deleted": "1/28/2018",
  "createdAt": "5/1/2017",
  "updatedAt": "10/6/2017",
  "categoryId": 4,
  "conditionId": 1,
  "itemstatusId": 1,
  "userId": 6
}, {
  "name": "S2000",
  "description": "Mellivora capensis",
  "price": "2.49",
  "manufacturer": "ENJUVIA",
  "model": "Thunderbird",
  "dimensions": "XL",
  "notes": "Senior Cost Accountant",
  "image": "https://robohash.org/molestiasmaximeeos.bmp?size=100x100&set=set1",
  "deleted": "1/14/2018",
  "createdAt": "9/10/2017",
  "updatedAt": "12/19/2016",
  "categoryId": 4,
  "conditionId": 1,
  "itemstatusId": 2,
  "userId": 7
}, {
  "name": "Genesis",
  "description": "Psophia viridis",
  "price": "8.82",
  "manufacturer": "Geotrichum candidum",
  "model": "Grand Prix",
  "dimensions": "2XL",
  "notes": "Teacher",
  "image": "https://robohash.org/quidictaprovident.bmp?size=100x100&set=set1",
  "deleted": "1/27/2018",
  "createdAt": "10/7/2017",
  "updatedAt": "1/2/2017",
  "categoryId": 4,
  "conditionId": 3,
  "itemstatusId": 1,
  "userId": 1
}, {
  "name": "Eurovan",
  "description": "Coluber constrictor",
  "price": "4.78",
  "manufacturer": "Cryselle",
  "model": "Entourage",
  "dimensions": "M",
  "notes": "Editor",
  "image": "https://robohash.org/etvoluptatumcommodi.jpg?size=100x100&set=set1",
  "deleted": "1/8/2018",
  "createdAt": "9/13/2017",
  "updatedAt": "11/18/2016",
  "categoryId": 3,
  "conditionId": 1,
  "itemstatusId": 2,
  "userId": 7
}, {
  "name": "Elise",
  "description": "Tiliqua scincoides",
  "price": "4.11",
  "manufacturer": "Nighttime Sleep Aid",
  "model": "Ram 1500 Club",
  "dimensions": "S",
  "notes": "Information Systems Manager",
  "image": "https://robohash.org/perferendissedconsequatur.bmp?size=100x100&set=set1",
  "deleted": "1/3/2018",
  "createdAt": "7/8/2017",
  "updatedAt": "12/8/2016",
  "categoryId": 2,
  "conditionId": 1,
  "itemstatusId": 1,
  "userId": 6
}, {
  "name": "911",
  "description": "Ardea cinerea",
  "price": "3.68",
  "manufacturer": "BROCCOLI SUN",
  "model": "Town Car",
  "dimensions": "M",
  "notes": "Senior Editor",
  "image": "https://robohash.org/temporaveleos.bmp?size=100x100&set=set1",
  "deleted": "1/4/2018",
  "createdAt": "12/11/2016",
  "updatedAt": "4/13/2017",
  "categoryId": 2,
  "conditionId": 2,
  "itemstatusId": 2,
  "userId": 1
}, {
  "name": "Neon",
  "description": "Semnopithecus entellus",
  "price": "1.05",
  "manufacturer": "Covergirl Smoothers Tinted Moisturizer",
  "model": "LR2",
  "dimensions": "M",
  "notes": "Teacher",
  "image": "https://robohash.org/nihilconsequunturarchitecto.jpg?size=100x100&set=set1",
  "deleted": "1/12/2018",
  "createdAt": "7/15/2017",
  "updatedAt": "8/22/2017",
  "categoryId": 1,
  "conditionId": 3,
  "itemstatusId": 1,
  "userId": 7
}, {
  "name": "Altima",
  "description": "Caiman crocodilus",
  "price": "1.24",
  "manufacturer": "Ciprofloxacin and Dextrose",
  "model": "Gallardo",
  "dimensions": "M",
  "notes": "Paralegal",
  "image": "https://robohash.org/impedititaquevel.jpg?size=100x100&set=set1",
  "deleted": "1/6/2018",
  "createdAt": "10/25/2017",
  "updatedAt": "11/27/2016",
  "categoryId": 3,
  "conditionId": 1,
  "itemstatusId": 1,
  "userId": 3
}, {
  "name": "Explorer Sport",
  "description": "Anathana ellioti",
  "price": "5.10",
  "manufacturer": "Trifluoperazine Hydrochloride",
  "model": "Vantage",
  "dimensions": "S",
  "notes": "Internal Auditor",
  "image": "https://robohash.org/nullalaborumpossimus.png?size=100x100&set=set1",
  "deleted": "1/19/2018",
  "createdAt": "2/19/2017",
  "updatedAt": "11/22/2016",
  "categoryId": 1,
  "conditionId": 1,
  "itemstatusId": 2,
  "userId": 6
}, {
  "name": "940",
  "description": "Choloepus hoffmani",
  "price": "4.40",
  "manufacturer": "LoHist PEB",
  "model": "Suburban 2500",
  "dimensions": "2XL",
  "notes": "Senior Cost Accountant",
  "image": "https://robohash.org/excepturitemporeinventore.bmp?size=100x100&set=set1",
  "deleted": "1/10/2018",
  "createdAt": "10/29/2017",
  "updatedAt": "8/4/2017",
  "categoryId": 3,
  "conditionId": 1,
  "itemstatusId": 2,
  "userId": 7
}] , {});
  },

  down : function (queryInterface, Sequelize) {
    queryInterface.bulkDelete('items',null )
  }
};